site_name: Actionable
repo_name: MohammadMD1383/Actionable
repo_url: https://github.com/MohammadMD1383/Actionable
theme:
  name: material
  
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - announce.dismiss
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
  
  icon:
    repo: fontawesome/brands/github
  
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode

plugins:
  - search
  - offline:
      enabled: !ENV [OFFLINE_DOCS, false]
  - file-filter:
      filter_nav: true
      exclude_glob:
        - 'assets/snippets/**'

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - abbr
  - md_in_html
  - tables
  - footnotes
  - def_list
