# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: nighly build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: |
        chmod +x gradlew
      shell: bash
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: buildPlugin
        
    - name: Create tag
      run: |
        cd build/distributions
        echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
        echo "TAG=nightly/$(ls | grep -iE '[0-9]+\.[0-9]+\.[0-9]+' --only-matching)+$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      shell: bash
        
    - name: Upload Nightly Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.TAG }}
        commit: ${{ env.COMMIT }}
        artifacts: "build/distributions/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
